workers_dev = true
type = "javascript"
name = "beth-price-feed-dev"
account_id = ""

[vars]
ENV = "development"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BETH_RATE_LIMITS = '{}'
BETH_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ETH_PRICE_LIMITS = '{}'
REQUEST_TIMEOUT = 10000


[build]
command = "npm run build"

[build.upload]
format = "service-worker"


[env.staging]
workers_dev = false
name = "beth-price-feed-staging"
route = ""
zone_id = ""

[env.staging.vars]
ENV = "staging"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BETH_RATE_LIMITS = '{}'
BETH_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ETH_PRICE_LIMITS = '{}'
REQUEST_TIMEOUT = 10000

[env.production]
workers_dev = false
name = "beth-price-feed"
route = ""
zone_id = ""

[env.production.vars]
ENV = "production"
SENTRY_PROJECT_ID = ""
SENTRY_KEY = ""
DEVIATION_BLOCK_OFFSETS = '[6500,260,40]'
BETH_RATE_LIMITS = '{}'
BETH_PRICE_LIMITS = '{"maxDeviations":[60,30,20]}'
STETH_RATE_LIMITS = '{"maxDeviations":[5,1,0.5]}'
ETH_PRICE_LIMITS = '{}'
REQUEST_TIMEOUT = 10000
